# **Experiment No : 2. Implement Feed Forward Network**

In [ ]:
import numpy as np

In [ ]:
def activation(z):
  return 1/(1+np.exp(-z))

def loss_function(target,output):
  return (1/len(target))*np.square(target-output)

In [ ]:
def forwardpass(x,w1,w2,b1,b2):
  weighted_sum1=np.dot(x,w1)+b1
  print("Weighted Sum from input layer :\n",weighted_sum1)

  h_in=activation(weighted_sum1)
  weighted_sum2=np.dot(h_in,w2)+b2
  print("Weighted Sum from hidden layer :\n",weighted_sum2)

  h_out=activation(weighted_sum2)
  return h_out


In [ ]:
x=np.array([[0.1, 0.3], [0.7, 0.2], [0.2, 0.4]])

targets=np.array([[0], [1], [1]])

w1= np.array([[0.8, 0.1], [0.9, 0.2]])
b1 = np.array([0.1, 0.2])

w2 = np.array([[0.7], [0.3]])
b2= np.array([0.1])


In [ ]:
final_output=forwardpass(x,w1,w2,b1,b2)
loss=loss_function(targets,final_output)

Weighted Sum from input layer :
 [[0.45 0.27]
 [0.84 0.31]
 [0.62 0.3 ]]
Weighted Sum from hidden layer :
 [[0.69757534]
 [0.76199123]
 [0.72748574]]


In [ ]:
print("Input Data :\n",x)
print("Output :\n",final_output)
print("Loss :\n",loss)

Input Data :
 [[0.1 0.3]
 [0.7 0.2]
 [0.2 0.4]]
Output :
 [[0.66764997]
 [0.6817859 ]
 [0.67425329]]
Loss :
 [[0.1485855 ]
 [0.03375341]
 [0.03537031]]
